# Change these first
owner: tiekoettercom # Your GitHub organization or username, where this repository lives
repo: searx-instances-uptime # The name of this repository
user-agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime

sites:

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  introTitle: "SearXNG and SearX status and uptime monitoring"
  introMessage: This status page lists all SearXNG and SearX instances from searx.space and checks their uptime every 10 minutes.
  cname: searx-instances.tiekoetter.com
  favicon: https://tiekoettercom-cdn.tiekoetter.cloud/wp-content/uploads/2022/04/searxng-wordmark.png
  faviconSvg: https://tiekoettercom-cdn.tiekoetter.cloud/wp-content/uploads/2022/04/searxng-wordmark.svg
  logoUrl: https://tiekoettercom-cdn.tiekoetter.cloud/wp-content/uploads/2022/04/searxng-wordmark.svg
  name: SearXNG and SearX instances status and uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: searx.space
      href: https://searx.space

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *"

commitMessages:
  commitAuthorName: "Tiekoetter Bot"
  commitAuthorEmail: "github-bot@tiekoetter.com"
