# Change these first
owner: tiekoettercom # Your GitHub organization or username, where this repository lives
repo: searx-instances-uptime # The name of this repository
user-agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime

sites:
  - name: searx.tiekoetter.com
    url: https://searx.tiekoetter.com/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: darmarit.org/searx
    url: https://darmarit.org/searx/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: paulgo.io
    url: https://paulgo.io/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.be
    url: https://searx.be/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: baresearch.org
    url: https://baresearch.org/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: copp.gg
    url: https://copp.gg/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: etsi.me
    url: https://etsi.me/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: freesearch.club
    url: https://freesearch.club/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: northboot.xyz
    url: https://northboot.xyz/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: nyc1.sx.ggtyler.dev
    url: https://nyc1.sx.ggtyler.dev/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: ooglester.com
    url: https://ooglester.com/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: opnxng.com
    url: https://opnxng.com/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: priv.au
    url: https://priv.au/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: s.mble.dk
    url: https://s.mble.dk/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: s.trung.fun
    url: https://s.trung.fun/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.bus-hit.me
    url: https://search.bus-hit.me/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.demoniak.ch
    url: https://search.demoniak.ch/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.gcomm.ch
    url: https://search.gcomm.ch/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.hbubli.cc
    url: https://search.hbubli.cc/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.im-in.space
    url: https://search.im-in.space/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.in.projectsegfau.lt
    url: https://search.in.projectsegfau.lt/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.inetol.net
    url: https://search.inetol.net/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.itstechtime.com
    url: https://search.itstechtime.com/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.leptons.xyz
    url: https://search.leptons.xyz/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.lvkaszus.pl
    url: https://search.lvkaszus.pl/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.mdosch.de
    url: https://search.mdosch.de/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.ononoki.org
    url: https://search.ononoki.org/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.projectsegfau.lt
    url: https://search.projectsegfau.lt/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.rabbit-company.com
    url: https://search.rabbit-company.com/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.rhscz.eu
    url: https://search.rhscz.eu/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.rowie.at
    url: https://search.rowie.at/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.sapti.me
    url: https://search.sapti.me/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.smnz.de
    url: https://search.smnz.de/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.upinmars.com
    url: https://search.upinmars.com/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: search.zzls.xyz
    url: https://search.zzls.xyz/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.ankha.ac
    url: https://searx.ankha.ac/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.baczek.me
    url: https://searx.baczek.me/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.catfluori.de
    url: https://searx.catfluori.de/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.cthd.icu
    url: https://searx.cthd.icu/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.daetalytica.io
    url: https://searx.daetalytica.io/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.fmac.xyz
    url: https://searx.fmac.xyz/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.fmhy.net
    url: https://searx.fmhy.net/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.headpat.exchange
    url: https://searx.headpat.exchange/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.juancord.xyz
    url: https://searx.juancord.xyz/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.kutay.dev
    url: https://searx.kutay.dev/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.lunar.icu
    url: https://searx.lunar.icu/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.namejeff.xyz
    url: https://searx.namejeff.xyz/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.nobulart.com
    url: https://searx.nobulart.com/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.oakleycord.dev
    url: https://searx.oakleycord.dev/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.ox2.fr
    url: https://searx.ox2.fr/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.perennialte.ch
    url: https://searx.perennialte.ch/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.sev.monster
    url: https://searx.sev.monster/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.si
    url: https://searx.si/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.techsaviours.org
    url: https://searx.techsaviours.org/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.tuxcloud.net
    url: https://searx.tuxcloud.net/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.work
    url: https://searx.work/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searx.zhenyapav.com
    url: https://searx.zhenyapav.com/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searxng.ch
    url: https://searxng.ch/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: searxng.site
    url: https://searxng.site/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: sex.finaltek.net
    url: https://sex.finaltek.net/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: sx.catgirl.cloud
    url: https://sx.catgirl.cloud/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: sx.t-1.org
    url: https://sx.t-1.org/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: www.gruble.de
    url: https://www.gruble.de/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: www.jabber-germany.de/searx
    url: https://www.jabber-germany.de/searx/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'
  - name: xo.wtf
    url: https://xo.wtf/
    expectedStatusCodes:
      - 200
      - 429
    headers:
      - 'User-Agent: SearX and SearXNG instances uptime checker @ github.com/tiekoettercom/searx-instances-uptime'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  introTitle: "SearXNG and SearX status and uptime monitoring"
  introMessage: This status page lists all SearXNG and SearX instances from searx.space and checks their uptime every 10 minutes.
  cname: searx-instances.tiekoetter.com
  baseUrl: /
  favicon: https://tiekoettercom-cdn.tiekoetter.cloud/wp-content/uploads/2022/04/searxng-wordmark.png
  faviconSvg: https://tiekoettercom-cdn.tiekoetter.cloud/wp-content/uploads/2022/04/searxng-wordmark.svg
  logoUrl: https://tiekoettercom-cdn.tiekoetter.cloud/wp-content/uploads/2022/04/searxng-wordmark.svg
  name: SearXNG and SearX instances status and uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: searx.space
      href: https://searx.space

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *"

commitMessages:
  commitAuthorName: "Tiekoetter Bot"
  commitAuthorEmail: "github-bot@tiekoetter.com"
